import Container from "@mui/material/Container";
import Head from "next/head";
import CommitHistory from "../components/CommitHistory";

const Home = () => {
  return (
    <div>
      <Head>
        <title>Github Commit History</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Container sx={{ py: 2 }}>
        <main>
          <CommitHistory />
        </main>
      </Container>
      <footer></footer>
    </div>
  );
};

export default Home;
